/**
 * This file is generated by 'file2variable-cli'
 * It is not mean to be edited by hand
 */
// tslint:disable
import { Tree } from "./index";

// @ts-ignore
export function treeTemplateHtml(this: Tree<any>) {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{class:_vm.rootClassName,attrs:{"role":"tree"}},[_c('ul',{class:_vm.containerClassName,attrs:{"role":"group"},on:{"dragstart":function($event){_vm.ondragstart($event)},"dragend":function($event){_vm.ondragend($event)},"dragover":function($event){_vm.ondragover($event)},"dragenter":function($event){_vm.ondragenter($event)},"dragleave":function($event){_vm.ondragleave($event)},"drop":function($event){_vm.ondrop($event)}}},_vm._l((_vm.data),function(child,i){return _c('node',{key:i,attrs:{"data":child,"last":i === _vm.data.length - 1,"checkbox":_vm.checkbox,"path":[i],"draggable":_vm.draggable,"root":_vm.data,"zindex":_vm.zindex,"preid":_vm.preid},on:{"toggle":function($event){_vm.ontoggle($event)},"change":function($event){_vm.onchange($event)}}})}))])}
// tslint:enable
